name: React TS CI

on:
  push:
    branches: [ "custom", "feature/*" ]
  pull_request:
    branches: [ "custom", "feature/*" ]

jobs:
  ci:

    runs-on: ubuntu-22.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.17.0
        cache: 'npm'

    - name: Verify Node version
      run: node -v

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npx tsc --noEmit

    - name: Run tests
      run: npm test -- --watchAll=false

    - name: Build project
      run: npm run build